spring:
  main.allow-bean-definition-overriding: true

# Dados da conexão PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/db_tgibank
    username: {name}
    password: {pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

# Configurações de envio de e-mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: {name}
    password: {pass}
    
    properties.mail.smtp:
      auth: true
      starttls.enable: true
    
# URL de callback
callbackUrl: {webhookUrl}
