spring:
  main.allow-bean-definition-overriding: true

# Dados da conexão PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/db_tgibank
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

# Configurações de envio de e-mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: filipe.xavier1928@gmail.com
    password: vhpqvovticazxtkn
    
    properties.mail.smtp:
      auth: true
      starttls.enable: true
    
# URL de callback
callbackUrl: https://webhook.site/f3c6f59c-6720-4b02-95d4-f14daac52a13